# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('political_division', models.PositiveSmallIntegerField(choices=[(1, b'Region'), (2, b'Provincia'), (3, b'Distrito')])),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo')),
            ],
        ),
    ]
