# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_relacion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='relaciones',
            field=models.ManyToManyField(blank=True, related_name='_producto_relaciones_+', to='catalogo.Producto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='seccion',
            field=models.CharField(blank=True, choices=[(b'genero', b'Genero'), (b'categoria', b'Categoria'), (b'estilo', b'Estilo'), (b'coleccion', b'Coleccion')], max_length=100, null=True),
        ),
    ]
