# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text=b'En nombre de La web', max_length=20)),
                ('logo', models.ImageField(upload_to=b'tienda')),
                ('descripcion', models.CharField(help_text=b'La descripcion Seo', max_length=150)),
            ],
        ),
    ]
