# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_finalizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
